### ISSUE TITLE
Cannot create folder

### ISSUE THREAD

**Issue by Chris2011** [timboudreau/adhoc-projects#1]
Hi,

today I've found your nice plugin. I tested it with a folder in my favorites. What I see is only subfolders inside the folder that I have added as a favorite folder can open as project right? Not the favorite folder selfs.

The second thing is when I open a folder as project and double click on a file inside it, for me its a javascript file, I got a warning (See screenshot). What is the problem with it? I use Netbeans 8.0 on a Windows 7 64 bit.
![error](https://cloud.githubusercontent.com/assets/795658/2755402/d705dc26-c967-11e3-845f-1c589773af1a.png)

Cheers,

Chris

**Comment by timboudreau** [comment]
This looks like a problem with your filesystem.  Does the user you're running as have write permission under c:\temp?  It looks like that's where your NetBeans settings directory is.  Or something really weird like the filesystem you're on not supporting paths that long or something.

At any rate, what's happening specifically is:  A write to NbPreferences (NetBeans internal implementation of the Preferences API) is failing with an IOException.  No specific idea why that is (your log file might show the stack trace - probably C:\temp\messages.log judging from your error), but it's lower level than anything this plugin can do something about.

**Comment by Chris2011** [comment]
The C:\temp is my user dir atm because I tested some plugins which I've found on github, also yours. So I have the permissions to write inside this folder, because netbeans started with this as the user dir: Netbeans.exe --userdir C:\temp. I use Windows 7 64bit which has a character length for folders and files up to 260 (file name + .ext). I will take a look into the messages.log which you mentioned, later.

Cheers,

Chris

**Comment by timboudreau** [comment]
The filename contains a `;` character, which is a path separator on Windows - that's the only thing that looks like it might be an issue in the screen shot.  Either way, the bug is in the NetBeans implementation of Preferences (a Preferences node's name is not restricted - if the implementation happens to create folders, it needs to escape things correctly) - if reproducible, I'd suggest [filing a bug here](https://netbeans.org/bugzilla/enter_bug.cgi?product=platform) with the log file attached and a link here.

**Comment by Chris2011** [comment]
The pathname is not set manually, not from me. The Path should looks like C:\Users... and so on. Now I execute netbeans with the normal user dir path C:\Users\Name\AppData\Roaming\Netbeans and it happens again. Here the stacktrace: http://pastebin.com/JTENa7jy

If its really not a bug in your addon I will file a bug for netbeans. Please give me feedback if its helpfull or not.

Cheers,

Chris

**Comment by timboudreau** [comment]
It probably is the `;` in the path causing problems on Windows.  I'm not sure why this is the first report of it, but I patched the module to use a different deliimiter on Windows.  Technically it should not be illegal to use a `;` in a preferences node name, but it was easy enough to just change it.

Version 1.17 is [available here](http://timboudreau.com/modules).

**Comment by Chris2011** [comment]
The problem still exists, not with ;; anymore but with --. It would be better if you can reopen the ticket, til you can fix it. :)

Stacktrace:
Caused: org.openide.filesystems.FSException: Cannot create folder --C:_Users_ChrisLE_Desktop_Test_folder in C:\temp\config (C:\temp\config\Preferences\com\timboudreau\adhoc\project--C:_Users_ChrisLE_Desktop_Test_folder).

**Comment by timboudreau** [comment]
Could you manually attempt to create that folder on the command line and see if that works or what the error message is if it doesn't?  It was a guess that the ;; was the problem.  I can't imagine what problem -- could solve, so that makes me think that we're chasing the wrong target here.

**Comment by Chris2011** [comment]
Ok, my steps. Open commandline, go to path C:\temp\config\Preferences\com\timboudreau\adhoc\project. crete folder with mkdir C:_Users_ChrisLE_Desktop_Test_Folder (I think this is not possible because of : after C but it was ok, it removed the C: from the beginning. And you see the folder which was created. You see a set of characters, which are not allowed in filenames or folders under windows on the right. C was added from me for the test on the right.
![adhocerror](https://cloud.githubusercontent.com/assets/795658/2782885/528a3454-cb26-11e3-8c47-fa7ecc9d669f.png)

**Comment by timboudreau** [comment]
Okay, that establishes that the problem is the `:` - that helps.

New version [is here](http://timboudreau.com/builds/job/Netbeans-Adhoc-Project-Plugin/lastSuccessfulBuild/artifact/adhoc-project/target/nbm/adhoc-project-1.18.nbm)

**Comment by Chris2011** [comment]
Great, it works for me :). Thx. Btw its only a hint. You create 1.17 and 1.18 but what you've done is only a bugfix so maybe 1.16.2 is ok for this. If you implement new features then 1.17 is good.

Cheers,

Chris
